//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Admin
    {
        public int Id { get; set; }
        public string Names { get; set; }
        public string Pasword { get; set; }
    }
}
