//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfapp.Employee.ParfumUI.DataModelMsSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleActivityMonitor
    {
        public int SaleId { get; set; }
        public string FullName { get; set; }
        public string Name { get; set; }
        public string Brend { get; set; }
        public string Gender { get; set; }
        public string Density { get; set; }
        public int Size { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Sale_Count { get; set; }
        public Nullable<int> Total { get; set; }
        public System.DateTime Date { get; set; }
    }
}
