//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfapp.Employee.ParfumUI.DataModelMsSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetailParfum
    {
        public int Id { get; set; }
        public int PriceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Brend { get; set; }
        public string Gender { get; set; }
        public string Density { get; set; }
        public int Size { get; set; }
        public int Price { get; set; }
        public int Number { get; set; }
    }
}
