//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace video26.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMedicine
    {
        public int Id { get; set; }
        public Nullable<int> MedicinesId { get; set; }
        public Nullable<int> SalesId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
