//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfapp.Users.ParfumUI.DataModelMsSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brend()
        {
            this.Parfumes = new HashSet<Parfume>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parfume> Parfumes { get; set; }
    }
}
