//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfapp.AdminPanel.ParfumUI.DataModelMsSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveUserTable
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsUser { get; set; }
        public bool IsActive { get; set; }
    }
}
