//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfapp.AdminPanel.ParfumUI.DataModelMsSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleteUpdateCategoryToParfum
    {
        public int Ids { get; set; }
        public string Header { get; set; }
        public string Category { get; set; }
    }
}
