//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfapp.AdminPanel.ParfumUI.DataModelMsSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleActivity
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Parfum { get; set; }
        public int Size { get; set; }
        public int Price { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Total { get; set; }
        public System.DateTime Date { get; set; }
    }
}
